services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: asst
    env_file:
      - .env
    volumes:
      - .:/app
    
    # command: ["/bin/bash", "-c", "sleep infinity"] # uncomment this line to keep alive for debug

    # send logs to shell (when not running debug or detached mode)
    tty: true
    stdin_open: true